matrix:
  include:
    # Frontend
    - language: node_js
      node_js: 9.4.9
      before_install:
        - cd frontend/
      install: yarn
      script:
        - yarn run lint
        - yarn run tsc
    # Backend
    - language: python
      python: 3.6
      before_install:
        - cd backend/
        - cp .env.example .env
      install: pip install -r requirements/dev.txt
      script:
        - flask test
    # Contracts
    - language: node_js
      node_js: 9.4.0
      before_install:
        - cd contract/
      install: yarn && yarn add global truffle ganache-cli
      before_script:
        - ganache-cli > /dev/null &
        - sleep 10
      script:
        - yarn run test
